# Generated by Django 4.2 on 2026-04-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('admitted_in', models.DateTimeField()),
                ('admitted_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Discharged', 'Discharged'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.room')),
            ],
            options={
                'db_table': 'admission',
            },
        ),
        migrations.CreateModel(
            name='AdmissionSupplyUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_date', models.DateField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplies')),
            ],
            options={
                'db_table': 'admission_supply_usage',
            },
        ),
    ]
