# Generated by Django 4.2 on 2026-05-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='line_total',
        ),
    ]
