# Generated by Django 4.2 on 2026-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Ward', 'Ward'), ('Private', 'Private'), ('Semi-Private', 'Semi-Private'), ('ICU', 'ICU'), ('Emergency', 'Emergency'), ('Operating', 'Operating')], max_length=100),
        ),
    ]
