# Generated by Django 4.2 on 2026-05-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymedicine',
            options={'ordering': ['medicine_name']},
        ),
        migrations.AlterModelOptions(
            name='supplies',
            options={'ordering': ['supply_name']},
        ),
    ]
