# Generated by Django 4.2 on 2026-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField()),
                ('age', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
